# Generated by Django 3.2.4 on 2021-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('title', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('seqsIndex', models.CharField(max_length=1)),
                ('pairsIndex', models.CharField(max_length=1)),
                ('seqs', models.TextField()),
                ('pairs', models.TextField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
