# Generated by Django 3.2.4 on 2021-06-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('protein1', models.CharField(max_length=60)),
                ('protein2', models.CharField(max_length=60)),
                ('sequence1', models.TextField()),
                ('sequence2', models.TextField()),
                ('probability', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
    ]
