# Generated by Django 3.2.4 on 2021-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pairs', models.FileField(upload_to='')),
                ('sequences', models.FileField(upload_to='')),
                ('predictions', models.FileField(upload_to='')),
            ],
        ),
    ]
