# Generated by Django 3.2.4 on 2021-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_auto_20210713_2052"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairsInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pairs", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PairsUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pairs", models.FileField(upload_to="pairs/")),
            ],
        ),
        migrations.CreateModel(
            name="PredictionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeqsInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqs", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SeqsUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqs", models.FileField(upload_to="seqs/")),
            ],
        ),
    ]
