# Generated by Django 3.2.6 on 2021-08-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0007_auto_20210817_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="queue_pos",
        ),
    ]
