# Generated by Django 3.2.4 on 2021-07-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_pairsinput_pairsupload_predictionjob_seqsinput_seqsupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionjob',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
