# Generated by Django 3.2.4 on 2021-07-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_fileprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sequences', models.FileField(upload_to='sequences/')),
                ('predictions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pairs', models.FileField(upload_to='pairs/')),
                ('sequences', models.FileField(upload_to='sequences/')),
                ('predictions', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Prediction',
            new_name='SinglePair',
        ),
        migrations.DeleteModel(
            name='FilePrediction',
        ),
    ]
